- name: Install virtualenv system dependencies
  apt:
    pkg:
      - python3-virtualenv
      - python3-wheel

- name: Install useful admin tools
  apt:
    pkg:
      - sqlite3

- name: Create install directory
  file:
    path: "{{ install_dir }}"
    state: directory
    owner: www-data
    mode: "755"

- name: Download
  git:
    repo: https://github.com/PeterJCLaw/code-submitter
    dest: "{{ install_dir }}"
    force: true
    version: 09e42aa7773cdd340f1cd0ebdb0b0ced61f84c0e
  notify:
    Restart code-submitter
  register: code_submitter_repo
  become_user: www-data

- name: Install configuration
  template:
    src: code-submitter.env
    dest: "{{ install_dir }}/.env"
    mode: "0600"
    owner: www-data
  notify:
    Restart code-submitter

- name: Install deploy requirements
  copy:
    src: deploy-requirements.txt
    dest: "{{ install_dir }}/deploy-requirements.txt"
    mode: "0600"
    owner: www-data
  notify:
    Restart code-submitter
  register: deploy_requirements

- name: Create credentials
  copy:
    content: "{}"
    dest: "{{ secrets_dir }}/code-submitter-credentials.yaml"
    owner: www-data
    force: false
    mode: "0600"
  notify:
    Restart code-submitter

- name: Install virtual environment
  pip:
    virtualenv: "{{ venv_dir }}"
    requirements: "{{ deploy_requirements.dest }}"
  notify:
    Restart code-submitter
  become_user: www-data
  when: deploy_requirements.changed or code_submitter_repo.changed  # noqa: no-handler - Use a handler to ensure execution order

- name: Install systemd service
  template:
    src: code-submitter.service
    dest: /etc/systemd/system/code-submitter.service
    mode: "0644"
  notify:
    Restart code-submitter

- name: Install nginx config
  template:
    src: nginx.conf
    dest: /etc/nginx/locations-enabled/code-submitter
    mode: "0644"
  notify:
    Reload nginx

- name: Check if database exists
  stat:
    path: "{{ install_dir }}/sqlite.db"
  register: database_file

- name: Install database  # noqa: no-changed-when - We want to always run this (it handles its own idempotency)
  shell:  # noqa: command-instead-of-shell - We need this to use `environment`
    argv:
      - "{{ venv_dir }}/bin/alembic"
      - upgrade
      - head
    chdir: "{{ install_dir }}"
  environment:
    PYTHONPATH: "{{ install_dir }}"
  become_user: www-data
  when: |
    code_submitter_repo.changed or
    database_file.stat.isreg is not defined or
    not database_file.stat.isreg

- name: Enable service
  service:
    name: code-submitter
    state: started
    enabled: true
