#!/bin/sh

# Wrapper script for applying changes via ansible.
#
# You are encouraged to run with `--check --diff` before applying any changes.

cd $(dirname $0)/..

exec ansible-playbook playbook.yml -i hosts --become --become-method=sudo "$@"
