- name: Install virtualenv system dependencies
  apt:
    pkg:
      - python3-virtualenv
      - python3-wheel

- name: Create user
  user:
    name: discord
    shell: /bin/nologin
    state: present
    create_home: false

- name: Create install directory
  file:
    path: "{{ install_dir }}"
    state: directory
    owner: discord
    mode: "755"

- name: Download
  git:
    repo: https://github.com/srobo/discord-bot
    dest: "{{ install_dir }}"
    force: true
    version: 3d05d5b4968dca15c59ce1ad3318398a419a0661
  notify:
    Restart discord-bot
  register: discord_bot_repo
  become_user: discord

- name: Bootstrap environment file
  copy:
    content: ""
    dest: "{{ install_dir }}/.env"
    force: false
    mode: "0600"
    owner: discord
  notify:
    Restart discord-bot

- name: Install virtual environment
  pip:
    virtualenv: "{{ venv_dir }}"
    name: file://{{ install_dir }}
  notify:
    Restart discord-bot
  become_user: discord
  when: discord_bot_repo.changed  # noqa: no-handler - Use a handler to ensure execution order

- name: Install systemd service
  template:
    src: discord-bot.service
    dest: /etc/systemd/system/discord-bot.service
    mode: "0644"
  notify:
    Restart discord-bot

- name: Enable service
  service:
    name: discord-bot
    state: started
    enabled: true
