---
# This is a dev VM created by Vagrant.

canonical_hostname: sr-competitionsvcs
secondary_hostnames:
  # See explanation in host_vars/competitionsvcs.studentrobotics.org.yml for why
  # we include the proxy hostname here.
  - sr-proxy

add_hsts_header: false
certbot_create_if_missing: false

postgresql_users:
  - name: volunteersys

postgresql_databases:
  - name: volunteersys  # required; the rest are optional
    owner: volunteersys
